### ISSUE TITLE
about page text alignment

### ISSUE THREAD

**Issue by dtylam** [nridyushmi/allaboutcats#3]
You mentioned you had difficulty making the text go to the left.
If you look at the div containing the text, the 'ml-auto' class is used, which means the left margin of the div will try to expand at much as possible. If you try 'mr-auto', the right margin will expand and the div will move left!

```
<div class="col-lg-3 ml-auto text-center">
          <p id="des" class="mb-10">This page is about the hairy friend ...
          </p>
          <a class="btn btn-light btn-xl js-scroll-trigger" href="..." target="_blank">...</a>
</div>
```

**Comment by nridyushmi** [comment]
Oh I will try this, and thanks for the comment!
